-- Database + RLS untuk Guru Ranting 01 Tambakboyo
create table if not exists public.admin_profiles(id uuid primary key references auth.users(id) on delete cascade,nama text,role text not null default 'editor' check(role in ('admin','editor')),created_at timestamptz default now());
create table if not exists public.guru(id bigint generated by default as identity primary key,nama text not null,jabatan text default 'Anggota / Guru',sekolah text,created_at timestamptz default now());
create table if not exists public.berita(id bigint generated by default as identity primary key,judul text not null,ringkasan text,tanggal text,created_at timestamptz default now());
create table if not exists public.agenda(id bigint generated by default as identity primary key,tanggal text not null,bulan text not null,judul text not null,lokasi text,created_at timestamptz default now());
create table if not exists public.galeri(id bigint generated by default as identity primary key,judul text not null,url text not null,created_at timestamptz default now());
create table if not exists public.dokumen(id bigint generated by default as identity primary key,judul text not null,deskripsi text,url text not null,created_at timestamptz default now());
create table if not exists public.informasi(id bigint generated by default as identity primary key,judul text not null,isi text,created_at timestamptz default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.admin_profiles where id=auth.uid()); $$;
create or replace function public.is_owner_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.admin_profiles where id=auth.uid() and role='admin'); $$;

alter table public.admin_profiles enable row level security;
alter table public.guru enable row level security;
alter table public.berita enable row level security;
alter table public.agenda enable row level security;
alter table public.galeri enable row level security;
alter table public.dokumen enable row level security;
alter table public.informasi enable row level security;

drop policy if exists "Public read guru" on public.guru; create policy "Public read guru" on public.guru for select using(true);
drop policy if exists "Admin write guru" on public.guru; create policy "Admin write guru" on public.guru for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Public read berita" on public.berita; create policy "Public read berita" on public.berita for select using(true);
drop policy if exists "Admin write berita" on public.berita; create policy "Admin write berita" on public.berita for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Public read agenda" on public.agenda; create policy "Public read agenda" on public.agenda for select using(true);
drop policy if exists "Admin write agenda" on public.agenda; create policy "Admin write agenda" on public.agenda for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Public read galeri" on public.galeri; create policy "Public read galeri" on public.galeri for select using(true);
drop policy if exists "Admin write galeri" on public.galeri; create policy "Admin write galeri" on public.galeri for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Public read dokumen" on public.dokumen; create policy "Public read dokumen" on public.dokumen for select using(true);
drop policy if exists "Admin write dokumen" on public.dokumen; create policy "Admin write dokumen" on public.dokumen for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Public read informasi" on public.informasi; create policy "Public read informasi" on public.informasi for select using(true);
drop policy if exists "Admin write informasi" on public.informasi; create policy "Admin write informasi" on public.informasi for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins read own profile" on public.admin_profiles; create policy "Admins read own profile" on public.admin_profiles for select using(auth.uid()=id);
drop policy if exists "Owner manage admins" on public.admin_profiles; create policy "Owner manage admins" on public.admin_profiles for all using(public.is_owner_admin()) with check(public.is_owner_admin());

-- Storage buckets. Jalankan jika bucket belum ada.
insert into storage.buckets(id,name,public) values('galeri','galeri',true) on conflict(id) do nothing;
insert into storage.buckets(id,name,public) values('dokumen','dokumen',true) on conflict(id) do nothing;
drop policy if exists "Public read media" on storage.objects;
create policy "Public read media" on storage.objects for select using(bucket_id in ('galeri','dokumen'));
drop policy if exists "Admin upload media" on storage.objects;
create policy "Admin upload media" on storage.objects for insert with check(bucket_id in ('galeri','dokumen') and public.is_admin());
drop policy if exists "Admin update media" on storage.objects;
create policy "Admin update media" on storage.objects for update using(bucket_id in ('galeri','dokumen') and public.is_admin());
drop policy if exists "Admin delete media" on storage.objects;
create policy "Admin delete media" on storage.objects for delete using(bucket_id in ('galeri','dokumen') and public.is_admin());

-- Setelah membuat user melalui Authentication > Users, jadikan ia pengurus:
-- insert into public.admin_profiles(id,nama,role) values('UUID_USER','Nama Pengurus','admin');